// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_VprTSizjEYvsMa4_F9EgP4O14RqCd-0',
    appId: '1:108343092318:web:7b6bd57303dfa4b8af40cf',
    messagingSenderId: '108343092318',
    projectId: 'mytimo',
    authDomain: 'mytimo.firebaseapp.com',
    storageBucket: 'mytimo.firebasestorage.app',
    measurementId: 'G-SWG405KVCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmejprPrh7oiOqqCzWXyQZ0fr2zwbLOss',
    appId: '1:108343092318:android:08c0ce8f0eb5ea8eaf40cf',
    messagingSenderId: '108343092318',
    projectId: 'mytimo',
    storageBucket: 'mytimo.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_VprTSizjEYvsMa4_F9EgP4O14RqCd-0',
    appId: '1:108343092318:web:7b6bd57303dfa4b8af40cf',
    messagingSenderId: '108343092318',
    projectId: 'mytimo',
    authDomain: 'mytimo.firebaseapp.com',
    storageBucket: 'mytimo.firebasestorage.app',
    measurementId: 'G-SWG405KVCB',
  );
}
